<a href="https://colab.research.google.com/github/kauebr/Projeto-Turing/blob/main/Teste_de_correla%C3%A7%C3%B5es_v_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## C√≥digo Inicial ‚Äî Levantamento Inicial, Visualiza√ß√£o e Pr√©-Processamento dos Dados

Neste bloco, realizo a visualiza√ß√£o inicial do dataset do **Sistema de Informa√ß√µes sobre Mortalidade (SIM)**. Tamb√©m inicio o c√°lculo de colunas dependentes da vari√°vel alvo.

üìÑ **Fonte dos dados (CSV):**  
https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIM/DO23OPEN.csv

üìò **Dicion√°rio de Dados (Data Dictionary):**  
https://diaad.s3.sa-east-1.amazonaws.com/sim/Mortalidade_Geral+-+Estrutura.pdf

 **Site Base dos dados:**  
https://opendatasus.saude.gov.br/dataset/sim/

# Importando Bibliotecas e dados

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
url = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIM/DO24OPEN.csv'
df = pd.read_csv(url, sep=';', encoding='latin1')  # usa ; como separador e latin1 para acentua√ß√£o

df.head()  # mostra as primeiras linhas

<ipython-input-8-cd27b95bc468>:2: DtypeWarning: Columns (65) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url, sep=';', encoding='latin1')  # usa ; como separador e latin1 para acentua√ß√£o

,contador,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,...,TPRESGINFO,TPNIVELINV,DTCADINF,MORTEPARTO,DTCONCASO,ALTCAUSA,CAUSABAS_O,TPPOS,TP_ALTERA,CB_ALT
0,1,1,2,19042024,2301.0,824.0,240490.0,24121964.0,459,1,...,NaN,NaN,NaN,NaN,NaN,NaN,I279,N,NaN,NaN
1,2,1,2,18012024,1030.0,824.0,240940.0,29041958.0,465,2,...,NaN,NaN,NaN,NaN,NaN,NaN,A09,N,NaN,NaN
2,3,1,2,22012024,700.0,824.0,241250.0,23031939.0,484,2,...,NaN,NaN,NaN,NaN,NaN,NaN,E112,N,NaN,NaN
3,4,1,2,24032024,1220.0,824.0,241050.0,10061944.0,479,2,...,NaN,NaN,NaN,NaN,NaN,NaN,G309,N,NaN,NaN
4,5,1,2,12012024,800.0,824.0,240320.0,8031950.0,473,2,...,NaN,NaN,NaN,NaN,NaN,NaN,I219,N,NaN,NaN

In [ ]:
# Exibindo o tamanho do modelo
df.shape

(1426346, 86)

In [ ]:
# Caculando tamanho do nosso conjunto de dados(dataframe)
1465610 * 86

126042460

# An√°lise explorat√≥ria

In [ ]:
df['CID10']

KeyError: 'CID10'

In [ ]:
df['CIRCOBITO'].isnull().sum()

np.int64(1283156)

In [ ]:
# Total de entradas
total = len(df)
coluna = 'CIRCOBITO'

# Verifica√ß√µes
nulos = df[coluna].isnull().sum()
vazios = (df[coluna] == '').sum()
nan_texto = (df[coluna].astype(str).str.upper() == 'NAN').sum()

# Num√©ricos (exclui NaN e vazios antes de checar)
numericos = pd.to_numeric(df[coluna], errors='coerce').notna().sum()

# Percentuais
print(f"An√°lise da coluna {coluna} (%):")
print(f"- Valores nulos (NaN/None): {nulos / total:.2%}")
print(f"- Valores em branco (''): {vazios / total:.2%}")
print(f"- Texto 'NaN': {nan_texto / total:.2%}")
print(f"- Valores num√©ricos v√°lidos: {numericos / total:.2%}")
print(f"- Temos {df.shape[0] - nulos} dados para trabalhar")

An√°lise da coluna CIRCOBITO (%):
- Valores nulos (NaN/None): 89.96%
- Valores em branco (''): 0.00%
- Texto 'NaN': 89.96%
- Valores num√©ricos v√°lidos: 10.04%
- Temos 143190 dados para trabalhar

In [ ]:
!pip install pysus

Collecting pysus
  Downloading pysus-0.15.0-py3-none-any.whl.metadata (1.3 kB)
Collecting Unidecode<2.0.0,>=1.3.6 (from pysus)
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Collecting aioftp<0.22.0,>=0.21.4 (from pysus)
  Downloading aioftp-0.21.4-py3-none-any.whl.metadata (6.1 kB)
Collecting bigtree<0.13.0,>=0.12.2 (from pysus)
  Downloading bigtree-0.12.5-py3-none-any.whl.metadata (28 kB)
Collecting cffi==1.15.1 (from pysus)
  Downloading cffi-1.15.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.1 kB)
Collecting dateparser<2.0.0,>=1.1.8 (from pysus)
  Downloading dateparser-1.2.1-py3-none-any.whl.metadata (29 kB)
Collecting dbfread==2.0.7 (from pysus)
  Downloading dbfread-2.0.7-py2.py3-none-any.whl.metadata (3.3 kB)
Collecting elasticsearch==7.16.2 (from elasticsearch[preprocessing]==7.16.2->pysus)
  Downloading elasticsearch-7.16.2-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting fastparquet>=2023.10.1 (from pysus)
  Downloading fastparquet-2024.11.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: humanize<5.0.0,>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from pysus) (4.12.3)
Collecting loguru<0.7.0,>=0.6.0 (from pysus)
  Downloading loguru-0.6.0-py3-none-any.whl.metadata (21 kB)
Collecting numpy==1.26.2 (from pysus)
  Downloading numpy-1.26.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 61.2/61.2 kB 4.5 MB/s eta 0:00:00
Requirement already satisfied: pandas<3.0.0,>=2.2.2 in /usr/local/lib/python3.11/dist-packages (from pysus) (2.2.2)
Requirement already satisfied: pyarrow>=11.0.0 in /usr/local/lib/python3.11/dist-packages (from pysus) (18.1.0)
Collecting pycparser==2.21 (from pysus)
  Downloading pycparser-2.21-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting pyreaddbc>=1.1.0 (from pysus)
  Downloading pyreaddbc-1.2.0.tar.gz (57 kB)
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 57.7/57.7 kB 5.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-dateutil==2.8.2 (from pysus)
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl.metadata (8.2 kB)
Collecting tqdm==4.64.0 (from pysus)
  Downloading tqdm-4.64.0-py2.py3-none-any.whl.metadata (57 kB)
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 57.3/57.3 kB 4.8 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /usr/local/lib/python3.11/dist-packages (from pysus) (4.14.0)
Collecting urwid<3.0.0,>=2.1.2 (from pysus)
  Downloading urwid-2.6.16-py3-none-any.whl.metadata (11 kB)
Collecting wget<4.0,>=3.2 (from pysus)
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Collecting urllib3<2,>=1.21.1 (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus)
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 50.1/50.1 kB 3.8 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus) (2025.4.26)
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil==2.8.2->pysus) (1.17.0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.11/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2025.2)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27,>=2015.06.24 in /usr/local/lib/python3.11/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2024.11.6)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.11/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (5.3.1)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.11/dist-packages (from fastparquet>=2023.10.1->pysus) (2.10.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from fastparquet>=2023.10.1->pysus) (2025.3.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from fastparquet>=2023.10.1->pysus) (24.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0.0,>=2.2.2->pysus) (2025.2)
Requirement already satisfied: pyyaml>=6 in /usr/local/lib/python3.11/dist-packages (from pyreaddbc>=1.1.0->pysus) (6.0.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.11/dist-packages (from urwid<3.0.0,>=2.1.2->pysus) (0.2.13)
Downloading pysus-0.15.0-py3-none-any.whl (1.4 MB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 1.4/1.4 MB 55.5 MB/s eta 0:00:00
Downloading cffi-1.15.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (462 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 462.6/462.6 kB 31.3 MB/s eta 0:00:00
Downloading dbfread-2.0.7-py2.py3-none-any.whl (20 kB)
Downloading elasticsearch-7.16.2-py2.py3-none-any.whl (385 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 385.7/385.7 kB 23.0 MB/s eta 0:00:00
Downloading numpy-1.26.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 18.2/18.2 MB 63.7 MB/s eta 0:00:00
Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 118.7/118.7 kB 10.6 MB/s eta 0:00:00
Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 247.7/247.7 kB 20.8 MB/s eta 0:00:00
Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 78.4/78.4 kB 7.2 MB/s eta 0:00:00
Downloading aioftp-0.21.4-py3-none-any.whl (37 kB)
Downloading bigtree-0.12.5-py3-none-any.whl (63 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 63.5/63.5 kB 5.5 MB/s eta 0:00:00
Downloading dateparser-1.2.1-py3-none-any.whl (295 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 295.7/295.7 kB 23.7 MB/s eta 0:00:00
Downloading fastparquet-2024.11.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 1.8/1.8 MB 59.2 MB/s eta 0:00:00
Downloading loguru-0.6.0-py3-none-any.whl (58 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 58.3/58.3 kB 5.0 MB/s eta 0:00:00
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 235.8/235.8 kB 18.1 MB/s eta 0:00:00
Downloading urwid-2.6.16-py3-none-any.whl (297 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 297.2/297.2 kB 23.0 MB/s eta 0:00:00
Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 144.2/144.2 kB 12.2 MB/s eta 0:00:00
Building wheels for collected packages: pyreaddbc, wget
  Building wheel for pyreaddbc (pyproject.toml) ... done
  Created wheel for pyreaddbc: filename=pyreaddbc-1.2.0-cp311-cp311-manylinux_2_35_x86_64.whl size=89810 sha256=a869a2d9f8272375dc3950431d1714a13a4de232679aa8a3b6f31ecdadb881b9
  Stored in directory: /root/.cache/pip/wheels/1c/24/ff/03c9d6c394a14bf0f14a18333ff9345e8ff1bc3c62b10b399e
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=a10f35015f6bfdef3c8645cbb87860d4f44bb2bce6651d4a2910ae363dd02230
  Stored in directory: /root/.cache/pip/wheels/40/b3/0f/a40dbd1c6861731779f62cc4babcb234387e11d697df70ee97
Successfully built pyreaddbc wget
Installing collected packages: wget, dbfread, urwid, urllib3, Unidecode, tqdm, python-dateutil, pycparser, numpy, loguru, bigtree, aioftp, elasticsearch, dateparser, cffi, pyreaddbc, fastparquet, pysus
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.4.0
    Uninstalling urllib3-2.4.0:
      Successfully uninstalled urllib3-2.4.0
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.1
    Uninstalling tqdm-4.67.1:
      Successfully uninstalled tqdm-4.67.1
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: pycparser
    Found existing installation: pycparser 2.22
    Uninstalling pycparser-2.22:
      Successfully uninstalled pycparser-2.22
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: cffi
    Found existing installation: cffi 1.17.1
    Uninstalling cffi-1.17.1:
      Successfully uninstalled cffi-1.17.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pygit2 1.18.0 requires cffi>=1.17.0, but you have cffi 1.15.1 which is incompatible.
dataproc-spark-connect 0.7.5 requires tqdm>=4.67, but you have tqdm 4.64.0 which is incompatible.
dopamine-rl 4.1.2 requires tqdm>=4.64.1, but you have tqdm 4.64.0 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.2 which is incompatible.
Successfully installed Unidecode-1.4.0 aioftp-0.21.4 bigtree-0.12.5 cffi-1.15.1 dateparser-1.2.1 dbfread-2.0.7 elasticsearch-7.16.2 fastparquet-2024.11.0 loguru-0.6.0 numpy-1.26.2 pycparser-2.21 pyreaddbc-1.2.0 pysus-0.15.0 python-dateutil-2.8.2 tqdm-4.64.0 urllib3-1.26.20 urwid-2.6.16 wget-3.2

In [ ]:
from pysus import SIM

# Carrega o m√≥dulo SIM
sim = SIM().load()

# Obt√©m os arquivos de 2023 para o estado de SP e grupo CID10
arquivos_2023 = sim.get_files("CID10", year=2023)

# Faz o download do arquivo (ou dos arquivos, se houver mais de um)
parquets = [arquivo.download() for arquivo in arquivos_2023]

# L√™ os dados como DataFrame
import pandas as pd

dfs = [pq.to_dataframe() for pq in parquets]

# Junta todos os dataframes, caso haja mais de um
df_2023 = pd.concat(dfs, ignore_index=True)

# Exibe as 5 primeiras linhas
print(df_2023.head())

TimeoutError: [Errno 110] Connection timed out

In [ ]:
df_2023.head()

,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,...,FONTES,TPRESGINFO,TPNIVELINV,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA,CONTADOR
0,1,2,01012023,0610,812,120070,26011941,481,1,4,...,,,,,,,,,,2067
1,1,2,01012023,1305,813,130180,20081966,456,2,4,...,,,,,,,,,,2146
2,1,2,01012023,0020,812,120030,15061968,454,2,1,...,,,,,,,,,,2196
3,1,2,01012023,1430,812,120045,14111965,457,1,4,...,,,,,,,,,,2839
4,1,2,01012023,1040,812,120035,12021958,464,2,4,...,,,,,,,,,,3066

In [ ]:
df_2023.columns

Index(['ORIGEM', 'TIPOBITO', 'DTOBITO', 'HORAOBITO', 'NATURAL', 'CODMUNNATU',
       'DTNASC', 'IDADE', 'SEXO', 'RACACOR', 'ESTCIV', 'ESC', 'ESC2010',
       'SERIESCFAL', 'OCUP', 'CODMUNRES', 'LOCOCOR', 'CODESTAB', 'ESTABDESCR',
       'CODMUNOCOR', 'IDADEMAE', 'ESCMAE', 'ESCMAE2010', 'SERIESCMAE',
       'OCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'GRAVIDEZ', 'SEMAGESTAC',
       'GESTACAO', 'PARTO', 'OBITOPARTO', 'PESO', 'TPMORTEOCO', 'OBITOGRAV',
       'OBITOPUERP', 'ASSISTMED', 'EXAME', 'CIRURGIA', 'NECROPSIA', 'LINHAA',
       'LINHAB', 'LINHAC', 'LINHAD', 'LINHAII', 'CAUSABAS', 'CB_PRE',
       'COMUNSVOIM', 'DTATESTADO', 'CIRCOBITO', 'ACIDTRAB', 'FONTE',
       'NUMEROLOTE', 'TPPOS', 'DTINVESTIG', 'CAUSABAS_O', 'DTCADASTRO',
       'ATESTANTE', 'STCODIFICA', 'CODIFICADO', 'VERSAOSIST', 'VERSAOSCB',
       'FONTEINV', 'DTRECEBIM', 'ATESTADO', 'DTRECORIGA', 'CAUSAMAT',
       'ESCMAEAGR1', 'ESCFALAGR1', 'STDOEPIDEM', 'STDONOVA', 'DIFDATA',
       'NUDIASOBCO', 'NUDIASOBIN', 'DTCADINV', 'TPOBITOCOR', 'DTCONINV',
       'FONTES', 'TPRESGINFO', 'TPNIVELINV', 'NUDIASINF', 'DTCADINF',
       'MORTEPARTO', 'DTCONCASO', 'FONTESINF', 'ALTCAUSA', 'CONTADOR'],
      dtype='object')

In [ ]:
df_2023.shape

(2931220, 87)

In [ ]:
df_2023['CIRCOBITO'].value_counts()

CIRCOBITO
     2623426
1     137052
3      83226
9      44982
2      32518
4      10016
Name: count, dtype: Int64

In [ ]:
df_suicidio = df_2023[df_2023['CIRCOBITO'] == '2']

In [ ]:
df_suicidio

,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,...,FONTES,TPRESGINFO,TPNIVELINV,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA,CONTADOR
24,1,2,02012023,1100,813,130260,25101981,441,1,4,...,,,,,,,,,,7886
39,1,2,04012023,1920,812,120020,27082003,419,1,4,...,,,,,,,,,,13647
137,1,2,14012023,1200,812,120040,25101980,442,1,4,...,,,,,,,,,,53256
166,1,2,17012023,0830,812,120060,15101961,461,2,4,...,,,,,,,,,,64794
192,1,2,20012023,0100,812,120040,21011996,426,1,4,...,,,,,,,,,,75977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2931022,1,2,23122023,0900,821,211000,17111987,436,2,2,...,,,M,,,,,,,1432214
2931049,1,2,24122023,2100,829,290320,29051988,435,1,1,...,,,,,,,,,,1435294
2931069,1,2,25122023,1410,841,411770,16051969,454,1,1,...,,,,,,,,,,1438454
2931083,1,2,26122023,,817,171750,13111981,442,1,4,...,,,,,,,,,,1442252
2931084,1,2,26122023,0030,817,170100,23102001,422,2,4,...,,,M,,,,,,,1442253

In [ ]:
df_suicidio['ASSISTMED'].value_counts()

ASSISTMED
2    19990
      5398
1     4840
9     2290
Name: count, dtype: Int64